### ISSUE TITLE
Current default port of proxy configuration is pre-configured as 14444 instead of 4444?

### ISSUE THREAD

**Issue by happywhitelake** [mikalv/test-i2p-browser#3]
Thanks @mikalv for building this all-in-one I2P browser bundle, I would make it easier for non-techical users to use I2P.

I tried the latest version and recoginize that the default proxy port is set to `14444` instead of `4444`, I am not sure if this is something caused by my MacOS but it was an easy fix for me, just changing the port back to `4444` and everything works normally.

Please have a look to see if this `14444` port is pre-configured in the bundle. Thank you!

![image](https://user-images.githubusercontent.com/11869279/64913717-f0ffaf80-d6f9-11e9-96ce-6c49fee809aa.png)

**Comment by mikalv** [comment]
Yea this should be resolved a while back now, forgot to update this issue. Beta 7 is out and I'll confirm it's long gone with it :) - You might need to reset your data directory if you still have the issue due to it's unfortunately been written to your browser profile settings already.
